model:
  filename: model/generated.go

models:
  User:
    model: github.com/jlightning/gqlgen/example/scalars/model.User
  Timestamp:
    model: github.com/jlightning/gqlgen/example/scalars/model.Timestamp
  SearchArgs:
    model: github.com/jlightning/gqlgen/example/scalars/model.SearchArgs
  Point:
    model: github.com/jlightning/gqlgen/example/scalars/model.Point
  ID:
    model: github.com/jlightning/gqlgen/example/scalars/model.ID
  Tier:
    model: github.com/jlightning/gqlgen/example/scalars/model.Tier
