// Code generated by github.com/jlightning/gqlgen, DO NOT EDIT.

package model

import (
	"external"
)

type Address struct {
	ID       external.ObjectID `json:"id"`
	Location *Point            `json:"location"`
}
